// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// ⚠️ IMPORTANTE ⚠️
/// Este archivo es un PLACEHOLDER. Debes reemplazarlo ejecutando:
///
///   dart pub global activate flutterfire_cli
///   flutterfire configure
///
/// Ese comando detectará tu proyecto de Firebase (el mismo donde habilitaste
/// el proveedor de Google, con el project id `project-492594867983`),
/// generará las apps de Android/iOS/Web/macOS que falten y sobrescribirá
/// este archivo con los valores reales (apiKey, appId, projectId, etc.).
///
/// Ejemplo de uso:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByf1jIUCYIhfjvwdf9QcztmCBUDPyLQWM',
    appId: '1:492594867983:web:9c63ad0f2bb59530aa187a',
    messagingSenderId: '492594867983',
    projectId: 'boccia-coaching',
    authDomain: 'boccia-coaching.firebaseapp.com',
    storageBucket: 'boccia-coaching.firebasestorage.app',
    measurementId: 'G-9C726GPXBR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNPI0SKKvCFpoPxHhtW3dy41oyIGd85kg',
    appId: '1:492594867983:android:5479ef0dda73a5a8aa187a',
    messagingSenderId: '492594867983',
    projectId: 'boccia-coaching',
    storageBucket: 'boccia-coaching.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBztGYqfuOoJH0YcjGXpK4iMGOH6hgfY00',
    appId: '1:492594867983:ios:2c1af0f30cc97bd4aa187a',
    messagingSenderId: '492594867983',
    projectId: 'boccia-coaching',
    storageBucket: 'boccia-coaching.firebasestorage.app',
    androidClientId: '492594867983-fitapckeuucj4ghuh1n1h9tffnukolin.apps.googleusercontent.com',
    iosClientId: '492594867983-nl167femsq663olrh22bvtmpjjc041fe.apps.googleusercontent.com',
    iosBundleId: 'com.example.bocciaCoachingApp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBztGYqfuOoJH0YcjGXpK4iMGOH6hgfY00',
    appId: '1:492594867983:ios:2c1af0f30cc97bd4aa187a',
    messagingSenderId: '492594867983',
    projectId: 'boccia-coaching',
    storageBucket: 'boccia-coaching.firebasestorage.app',
    androidClientId: '492594867983-fitapckeuucj4ghuh1n1h9tffnukolin.apps.googleusercontent.com',
    iosClientId: '492594867983-nl167femsq663olrh22bvtmpjjc041fe.apps.googleusercontent.com',
    iosBundleId: 'com.example.bocciaCoachingApp',
  );
}
